import { Component, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { CustomerService } from '../../services/customer.service';

@Component({
    selector: 'app-add-customer',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, RouterModule],
    templateUrl: './add-customer.component.html',
    styleUrls: ['./add-customer.component.css']
})
export class AddCustomerComponent {
    private fb = inject(FormBuilder);
    private customerService = inject(CustomerService);
    private router = inject(Router);
    private cdr = inject(ChangeDetectorRef);

    customerForm: FormGroup = this.fb.group({
        name: ['', Validators.required],
        address: ['', Validators.required],
        principal: [null, [Validators.required, Validators.min(0)]],
        interestRate: [null, [Validators.required, Validators.min(0)]],
        timePeriod: [null, [Validators.required, Validators.min(0)]]
    });

    isSubmitting = false;
    errorMessage = '';
    successMessage = '';

    onAdd_or_Submit() {
        this.router.navigate(['/all-customers']);
    }

    onSubmit() {
        if (this.customerForm.valid) {
            this.isSubmitting = true;
            this.errorMessage = '';
            this.successMessage = '';
            const formValue = this.customerForm.value;

            // Map form values to Customer object structure expected by service
            // Note: ID will be generated by backend
            const newCustomer = {
                ...formValue,
                id: '',
                status: 'active'
            };

            this.customerService.addCustomer(newCustomer).subscribe({
                next: (response: any) => {
                    this.isSubmitting = false;
                    console.log('Customer added successfully:', response);

                    // Extract customer name and principal amount from form
                    const customerName = formValue.name;
                    const principalAmount = formValue.principal;
                    this.successMessage = `✅ Customer "${customerName}" with "${principalAmount}" amount added successfully`;

                    // Force change detection to update UI
                    this.cdr.detectChanges();

                    // Clear form after success
                    this.customerForm.reset();

                    // Clear cache to ensure all-customers page loads fresh data
                    this.customerService.clearCache();

                    // Navigate to all-customers page after showing success message for 1.5 seconds
                    setTimeout(() => {
                        this.router.navigate(['/all-customers'], { state: { forceReload: true } });
                    }, 1500);
                },
                error: (err: any) => {
                    console.error('Error adding customer', err);
                    this.isSubmitting = false;

                    // Check if it's a duplicate customer error
                    if (err.status === 409 || (err.error && err.error.includes('already exists'))) {
                        this.errorMessage = `❌ Customer "${formValue.name}" with "${formValue.principal}" amount already exists`;
                    } else if (err.status === 400) {
                        this.errorMessage = `❌ Invalid data provided. Please check all fields and try again.`;
                    } else {
                        this.errorMessage = `❌ Error: ${err.error || err.message || 'Failed to add customer. Please try again.'}`;
                    }

                    // Force change detection to update UI
                    this.cdr.detectChanges();
                }
            });
        } else {
            this.customerForm.markAllAsTouched();
            this.errorMessage = '❌ Please fill in all required fields correctly.';
        }
    }
}
